### ISSUE TITLE
Ingestion in progress ribbon/ progress bar

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#54]
## Problem / Motivation
 
- WHO As a production team member or journal staff
- WHEN and WHERE anywhere on the dashboard
- WHAT I would like to know when an article is being ingested
- WHY so that I know if the article sent from the production system went through and so that I can anticipate an article arriving/updating

## Proposed solution
- An animated blue indeterminate progress bar/ ribbon underneath the header to signify that the system picked up something (see screenshot below and a similar example at https://material.io/design/components/progress-indicators.html) 
- When any run (1 or more) is in progress we show the blue ribbon feedback
- The progress ribbon is displayed if at least one run is not complete
- It disappears when complete

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Clarification needed and assumptions

- A question
- An assumption

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

<img width="1149" alt="02-ingesting_png" src="https://user-images.githubusercontent.com/39725642/47027062-a29b0700-d15e-11e8-9684-8b64c3bd5ac3.png">

**Comment by Melissa37** [comment]
>sent from Kriya

Suggest changing to "sent from the production system"
(more generic)

Otherwise sounds OK 👍

**Comment by Maelplaine** [comment]
Thanks @Melissa37 it's done

**Comment by chugginselifesciences** [comment]
The progress indicator will, at least for MVP, need to show "indeterminate" progress. In other words an animation to demonstrate progress, but it will continue animating until done, instead of filling a bar to represent "progress" towards a done state...

https://material.io/design/components/progress-indicators.html#linear-progress-indicators

I would like to work on the animation once we have something built or prototyped. But the google indeterminate progress bar may be a good starting place, or suitable for MVP.
